CREATE TABLE IF NOT EXISTS `TB_USER_TOKEN`(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID bigint NOT NULL,
    TOKEN LONGTEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_TB_USER_TOKEN_USER_ID FOREIGN KEY (USER_ID) REFERENCES TB_USER(ID)
);