CREATE TABLE IF NOT EXISTS `TB_USER_CONDOMINIUM`(
    USER_ID bigint NOT NULL,
    CONDOMINIUM_ID bigint NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `UNIQUE_KEY_TB_CONDOMINIUM_X_USER` (`USER_ID`,`CONDOMINIUM_ID`),
    CONSTRAINT FK_TB_USER_CONDOMINIUM_USER_ID FOREIGN KEY (USER_ID) REFERENCES TB_USER(ID),
    CONSTRAINT FK_TB_USER_CONDOMINIUM_CONDOMINIUM_ID FOREIGN KEY (CONDOMINIUM_ID) REFERENCES TB_CONDOMINIUM(ID)
);