CREATE TABLE IF NOT EXISTS `TB_PERMISSION`(
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION MEDIUMTEXT NOT NULL,
    CONSTANT VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP
);