CREATE TABLE IF NOT EXISTS `TB_PERSON`(
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(200) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    USER_ID bigint NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_TB_PERSON_USER_ID FOREIGN KEY (USER_ID) REFERENCES TB_USER(ID)
);