CREATE TABLE IF NOT EXISTS `TB_CONDOMINIUM`(
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FANTASY_NAME VARCHAR(200) NOT NULL,
    CORPORATE_NAME MEDIUMTEXT NULL,
    LOGO LONGTEXT NULL,
    ACTIVE boolean NOT NULL DEFAULT true,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP
);