CREATE TABLE IF NOT EXISTS `TB_USER_PROFILE`(
    USER_ID bigint NOT NULL,
    PROFILE_ID bigint NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `UNIQUE_KEY_TB_USER_PROFILE` (`USER_ID`,`PROFILE_ID`),
    CONSTRAINT FK_TB_USER_PROFILE_USER_ID FOREIGN KEY (USER_ID) REFERENCES TB_USER(ID),
    CONSTRAINT FK_TB_USER_PROFILE_PROFILE_ID FOREIGN KEY (PROFILE_ID) REFERENCES TB_PROFILE(ID)
);