CREATE TABLE IF NOT EXISTS `TB_USER`(
    ID bigint NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(320) NOT NULL,
    PASSWORD longtext NOT NULL,
	ACTIVE boolean NOT NULL DEFAULT true,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `UNIQUE_KEY_TB_USER_USERNAME` (`USERNAME`)
);