CREATE TABLE IF NOT EXISTS `TB_SYSTEM_LOG` (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EXCEPTION VARCHAR(100) NOT NULL,
    MESSAGE LONGTEXT NOT NULL,
    FILE VARCHAR(100) NOT NULL,
    LINE SMALLINT NOT NULL,
    TRACE LONGTEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP
);